name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  dio: ^4.0.6
  response_parser: 
    path: ../
  freezed_annotation: ^2.1.0
